### ISSUE TITLE
Help for Generating Voxel terrain

### ISSUE THREAD

**Issue by EmpireWorld** [ricardojmendez/LibNoise.Unity#13]
Hi.

How can i generate minecraft like terrains using this library?

Should i treat 0 and lower as air and higher than 0 solid?

Thanks.

**Comment by ricardojmendez** [comment]
Hi,

That depends entirely on the type of terrain you're generating and how you want to look at the data. I'm afraid I can't provide a blanket answer - it's all up to your implementation.

Cheers!

**Comment by EmpireWorld** [comment]
Hi.

I just need a little help, a little example.

Can you help?

Thanks.

**Comment by Andros-Spica** [comment]
Hi Hasan,I strongly recommend this tutorial:http://alexstv.com/index.php/category/voxel-tutorialYou could probably improve it, once you get the idea.Good luck!




Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Hasan Bayat <notifications@github.com> Date: 5/27/17  01:36  (GMT-05:00) To: "ricardojmendez/LibNoise.Unity" <LibNoise.Unity@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [ricardojmendez/LibNoise.Unity] Help for Generating Voxel terrain (#13) 
Hi.
How can i generate minecraft like terrains using this library?
Should i treat 0 and lower as air and higher than 0 solid?
Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ricardojmendez/LibNoise.Unity","title":"ricardojmendez/LibNoise.Unity","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ricardojmendez/LibNoise.Unity"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Help for Generating Voxel terrain (#13)"}],"action":{"name":"View Issue","url":"https://github.com/ricardojmendez/LibNoise.Unity/issues/13"}}}
